services:
  app:
    build: .
    image: project-juggler:latest
    container_name: project-juggler
    restart: unless-stopped
    ports:
      - "127.0.0.1:8005:80"
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage/app

volumes:
  storage:
